const img = ['img/Amalfi Coast .jpeg','img/Astotin Lake.jpeg',
'img/Bibury, The Cotswolds.jpeg',
'img/Borobudur.jpeg',
'img/Central Park.jpeg',
'img/Cinque Terre.jpeg',
'img/Eiffel Tower.jpeg',
'img/Grand Canyon.jpeg',
'img/Iceland.jpeg',
'img/Lake Como.jpeg',
'img/Land\'s End, Cornwall.jpeg',
'img/Lofoten, Norway.jpeg',
'img/Machu Picchu.jpeg',
'img/Mount Fuji.jpeg',
'img/Niagara Falls.jpeg',
'img/Norway.jpeg',
'img/Oxford, Oxfordshire.jpeg',
'img/Petra.jpeg',
'img/Pompeii.jpeg',
'img/Prague Castle.jpeg',
'img/Pyramids of Giza.jpeg',
'img/St. Michael\'s Mount, Cornwall.jpeg',
'img/Statue of Liberty.jpeg',
'img/Stonehenge.jpeg',
'img/Sydney Opera House.jpeg',
'img/The Acropolis.jpeg',
'img/The Colosseum.jpeg',
'img/The Leaning Tower of Pisa.jpeg',
'img/The Louvre.jpeg',
'img/The Roman Forum.jpeg',
'img/The Taj Mahal.jpeg',
'img/Tuscany.jpeg',
'img/Venice.jpeg',
'img/Windermere, Lake District.jpeg',
'img/York, North Yorkshire.jpeg',
'img/Zermatt, Switzerland.jpeg']
const chosenImg = img[Math.floor(Math.random()*img.length)]
const bgImgElement = document.createElement('img')
bgImgElement.src = `${chosenImg}`

document.body.appendChild(bgImgElement)
